### ISSUE TITLE
keep node_id as in JSON input

### ISSUE THREAD

**Issue by lforesta** [Open-EO/openeo-pg-parser-python#26]
Currently a `_X`, where X is a number, is added to each node_id in the python object. Since the process graph node ids must already be unique, we can keep them unchanged, no?

This may simplify things in case one needs to access information about the PG from two different programs, or at different processing stages, and relies on the node_id to retrieve job information.

**Comment by claxn** [comment]
I am not so sure. In my opinion an ID should be unique, even if we said now that process graph nodes need to have a unique name. I would like to keep this at least internally, because this also ensures backward compatibility and is more flexible. In your example one always can use the node names (this remains unchanged and is defined by the user) to compare job information. So finally the back-end decides if it uses node IDs or node names for writing job information. 
@m-mohr what is your opinion on this? How is this with the JS parser? Should I introduce a check in the pg parser that all node names need to be unique?

**Comment by m-mohr** [comment]
I'm not exactly sure what node ids and node names are for you, but they keys in the process graphs must be unique in it's scope (the same level in the process graph). Sub process graphs can have the same IDs again, although this can be confusing, so should be avoided if possible.

The JS parser doesn't check anything as per definition the node ids can't be used multiple times, object keys are unique by definition, otherwise the process (graph) is invalid.

**Comment by lforesta** [comment]
@claxn given the parsed process_graph I can access a node content by both name and id? In this case I think my issue is solved, since I can use the name, which I know from the original openEO process graph.
Could you provide an example on how to access one node by name, without having to loop and match?

**Comment by claxn** [comment]
@m-mohr thanks for the clarification. Node names are the node names/tags given by the user, and node IDs are created by the parser (node name + counter) to achieve a unique behaviour. I will add a validation step, which checks if there are two nodes with the same name within the same scope. 

@lforesta please have look at the commit above or at the latest version of the branch `bug_fixes`. I have implemented indexing by node ID and node name now. If everything works fine, please close the issue.

**Comment by claxn** [comment]
@m-mohr : actually a test is also not necessary in Python, as also here per definition Python dictionary keys are overwritten.
